### ISSUE TITLE
group-level searchlight hyperalignment

### ISSUE THREAD

**Issue by theomarins** [neuroboros/neuroboros.github.io#2]
Hi, is it possible to run a group-level searchlight hyperalignment, instead of working with only two brains, as the tutorials show?

**Comment by feilong** [comment]
Yes, there is.  I suppose you'll be interested in the `searchlight_template` function (https://github.com/feilong/hyperalignment/blob/dev/src/hyperalignment/searchlight.py#L61).

After creating the template, you can hyperalign each brain to the template for additional analysis.

**Comment by theomarins** [comment]
Thank you for the quick reply.

Is there a place where I can read about its parameters and how to apply/modify them?

Best,



From: Feilong Ma ***@***.***>
Reply-To: "neuroboros/neuroboros.github.io" ***@***.***>
Date: Tuesday, December 17, 2024 at 22:38
To: "neuroboros/neuroboros.github.io" ***@***.***>
Cc: theo marins ***@***.***>, Author ***@***.***>
Subject: Re: [neuroboros/neuroboros.github.io] group-level searchlight hyperalignment (Issue #2)


Yes, there is. I suppose you'll be interested in the searchlight_template function (https://github.com/feilong/hyperalignment/blob/dev/src/hyperalignment/searchlight.py#L61).

After creating the template, you can hyperalign each brain to the template for additional analysis.

**Comment by feilong** [comment]
The documentation is under preparation, but let me know if you have any questions.

**Comment by theomarins** [comment]
Thank you. One question: I am using nb.load to import my data. Is there a way to import data separately for each hemisphere, according to the nb standards, or I should do it manually?


From: Feilong Ma ***@***.***>
Reply-To: "neuroboros/neuroboros.github.io" ***@***.***>
Date: Wednesday, December 18, 2024 at 14:53
To: "neuroboros/neuroboros.github.io" ***@***.***>
Cc: theo marins ***@***.***>, Author ***@***.***>
Subject: Re: [neuroboros/neuroboros.github.io] group-level searchlight hyperalignment (Issue #2)


The documentation is under preparation, but let me know if you have any questions.

**Comment by feilong** [comment]
We typically use this `process` package to preprocess the data, and the preprocessed data can be loaded by neuroboros directly.
When you use `nb.load`, there is an `lr` parameter which you can use to specify the hemisphere.

**Comment by theomarins** [comment]
My data was preprocessed using fMRIprep and first level using nilearn. My surface z_maps have shape of (288,10242).
Is it possible to proceed to searchlight_template from here?

From: Feilong Ma ***@***.***>
Reply-To: "neuroboros/neuroboros.github.io" ***@***.***>
Date: Friday, December 20, 2024 at 18:47
To: "neuroboros/neuroboros.github.io" ***@***.***>
Cc: theo marins ***@***.***>, Author ***@***.***>
Subject: Re: [neuroboros/neuroboros.github.io] group-level searchlight hyperalignment (Issue #2)


We typically use this process package to preprocess the data, and the preprocessed data can be loaded by neuroboros directly.
When you use nb.load, there is an lr parameter which you can use to specify the hemisphere.

**Comment by feilong** [comment]
Yes, you can. Just make sure you use the correct searchlights (nb.sls) and
cortical mask.  It’s likely the data is in fsavg-ico32 space.

**Comment by gustavopamplona** [comment]
Hi Feilong,

I'm working together with Theo with the same data. I've got some questions...

- How to use nb.load with the rl parameter to define the hemisphere?
- The data we have is a dictionary with several levels. More specifically, it's comprised of a pkl file and, when loaded with nb.load, the result is data['session']['subject']['run']. I was wondering if there's a way to work with it in the same structure you have, for example, dset = nb.Forrest()

Many thanks!
Gustavo

**Comment by gustavopamplona** [comment]
Hi Feilong,

Yes, we know that the data is organized as data['session']['subject']['run'] (I am in touch with the collaborator). The question would rather be how to adapt it to the neuroboros format. 
I understood that, if one uses 'process', the data ends up in the neuroboros format automatically. But this is a customized data. Would there be a way to manually adapt arrays to the neuroboros format? If so and not a pain, could you please give an example with exemplary matrices?

Many thanks in advance. Cheers,
Gustavo

**Comment by feilong** [comment]
Hi Gustavo,

My point is `data['session']['subject']['run']` would probably give you a NumPy array that you can directly use.  However, I don't have access to your customized data, so I can only make a guess.  It would be much easier to let your collaborator handle it and convert it to the right format.

If you take a look at this example https://neuroboros.github.io/tutorials/neuroimaging_data_matrix.html
Ideally you'll get your `dm` in your own way, probably through your collaborator, and then you can follow the rest of the tutorial.

Best,
Feilong
